project_id = "ontrack"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:8081"
enable_confirmations = false

[auth.email]
enable_signup = true
