import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { getSession, pauseSession, resumeSession, endSession } from '@/features/sessions/api';
import { Screen, ErrorMessage } from '@/components/ui/Screen';
import { ActionButton } from '@/components/ui/ActionButton';
import { colors } from '@/theme/colors';

export default function FocusSession() { const { sessionId } = useLocalSearchParams<{ sessionId: string }>(); const router = useRouter(); const [session, setSession] = useState<any>(); const [error, setError] = useState<string | null>(null); const [now, setNow] = useState(Date.now()); useEffect(() => { getSession(sessionId).then(setSession).catch((e) => setError(e.message)); const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, [sessionId]); const act = async (fn: (id: string) => Promise<any>) => { try { setSession(await fn(sessionId)); } catch (e: any) { setError(e.message); } }; const remaining = session?.expected_end_at ? Math.max(0, Math.ceil((Date.parse(session.expected_end_at) - now) / 60000)) : null; return <Screen title="Focus Session" onBack={() => router.back()}><ErrorMessage message={error} /><View style={styles.focus}><Text style={styles.kicker}>FOCUS MODE</Text><Text style={styles.timer}>{remaining === null ? '--' : `${remaining}m`}</Text><Text style={styles.status}>{session?.status ?? 'Loading'}</Text>{session?.status === 'IN_PROGRESS' && <ActionButton title="Pause" onPress={() => void act(pauseSession)} />}{session?.status === 'PAUSED' && <ActionButton title="Resume" onPress={() => void act(resumeSession)} />}<ActionButton title="End early → Review" secondary onPress={() => void endSession(sessionId, true).then(() => router.replace(`/session/${sessionId}/review` as any)).catch((e) => setError(e.message))} /></View></Screen>; }
const styles = StyleSheet.create({ focus: { minHeight: 440, backgroundColor: colors.surface, borderRadius: 28, alignItems: 'center', justifyContent: 'center', padding: 28, gap: 20 }, kicker: { color: colors.primary, letterSpacing: 2, fontWeight: '800' }, timer: { color: colors.text, fontSize: 84, fontWeight: '800' }, status: { color: colors.muted, fontSize: 18, marginBottom: 20 } });
