import { useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { completeSessionReview } from '@/features/dashboard/api';
import { Screen, ErrorMessage } from '@/components/ui/Screen';
import { ActionButton } from '@/components/ui/ActionButton';
import { colors } from '@/theme/colors';

export default function ReviewSession() { const { sessionId } = useLocalSearchParams<{ sessionId: string }>(); const router = useRouter(); const [progress, setProgress] = useState('40'); const [minutes, setMinutes] = useState('25'); const [note, setNote] = useState(''); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const submit = async () => { setLoading(true); try { const result: any = await completeSessionReview({ p_session_id: sessionId, p_progress_after: Number(progress), p_actual_minutes: Number(minutes), p_result_note: note || null }); router.replace(result.can_create_follow_up ? `/session/${sessionId}` as any : '/(tabs)/today'); } catch (e: any) { setError(e.message); } finally { setLoading(false); } }; return <Screen title="Post-Session Review" onBack={() => router.back()}><View style={styles.card}><Text style={styles.title}>How did it go?</Text><Text style={styles.label}>Progress after (%)</Text><TextInput value={progress} onChangeText={setProgress} keyboardType="number-pad" style={styles.input} /><Text style={styles.label}>Actual minutes</Text><TextInput value={minutes} onChangeText={setMinutes} keyboardType="number-pad" style={styles.input} /><Text style={styles.label}>Result note</Text><TextInput value={note} onChangeText={setNote} multiline style={[styles.input, styles.note]} /><ErrorMessage message={error} /><ActionButton title="Save review" loading={loading} onPress={() => void submit()} /></View></Screen>; }
const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, borderRadius: 24, padding: 24, gap: 12 }, title: { color: colors.text, fontSize: 28, fontWeight: '800', marginBottom: 8 }, label: { color: colors.muted, fontWeight: '600' }, input: { borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 12, color: colors.text }, note: { minHeight: 90, textAlignVertical: 'top' } });
