import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { createMilestone, createTask, deleteDeadline, deleteMilestone, deleteTask, getDeadline, updateDeadline, updateMilestone, updateTask, type Priority } from '@/features/plans/api';
import { Screen, ErrorMessage } from '@/components/ui/Screen';
import { ActionButton } from '@/components/ui/ActionButton';
import { colors } from '@/theme/colors';

const iso = (date: string) => new Date(`${date}T23:59:59`).toISOString();
const dateOnly = (date?: string) => date ? new Date(date).toISOString().slice(0, 10) : '';

export default function DeadlineDetail() {
  const { deadlineId } = useLocalSearchParams<{ deadlineId: string }>(); const router = useRouter();
  const [deadline, setDeadline] = useState<any>(); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const [deadlineTitle, setDeadlineTitle] = useState(''); const [deadlineDate, setDeadlineDate] = useState(''); const [deadlinePriority, setDeadlinePriority] = useState<Priority>('MEDIUM');
  const [milestoneId, setMilestoneId] = useState<string | null>(null); const [milestoneTitle, setMilestoneTitle] = useState(''); const [milestoneDate, setMilestoneDate] = useState('');
  const [taskId, setTaskId] = useState<string | null>(null); const [taskMilestoneId, setTaskMilestoneId] = useState(''); const [taskTitle, setTaskTitle] = useState(''); const [taskPriority, setTaskPriority] = useState<Priority>('MEDIUM');
  const load = async () => { try { const data: any = await getDeadline(deadlineId); setDeadline(data); setDeadlineTitle(data.title); setDeadlineDate(dateOnly(data.due_at)); setDeadlinePriority(data.priority ?? 'MEDIUM'); } catch (e: any) { setError(e.message); } };
  useEffect(() => { void load(); }, [deadlineId]);
  const saveDeadline = async () => { setLoading(true); try { await updateDeadline(deadlineId, { title: deadlineTitle, due_at: iso(deadlineDate), priority: deadlinePriority }); await load(); } catch (e: any) { setError(e.message); } finally { setLoading(false); } };
  const saveMilestone = async () => { setLoading(true); try { const input = { deadline_id: deadlineId, title: milestoneTitle, target_at: iso(milestoneDate) }; if (milestoneId) await updateMilestone(milestoneId, input); else await createMilestone(input); setMilestoneId(null); setMilestoneTitle(''); setMilestoneDate(''); await load(); } catch (e: any) { setError(e.message); } finally { setLoading(false); } };
  const saveTask = async () => { setLoading(true); try { const input = { milestone_id: taskMilestoneId, title: taskTitle, priority: taskPriority }; if (taskId) await updateTask(taskId, input); else await createTask(input); setTaskId(null); setTaskMilestoneId(''); setTaskTitle(''); await load(); } catch (e: any) { setError(e.message); } finally { setLoading(false); } };
  const confirm = (title: string, onDelete: () => Promise<void>) => Alert.alert(`Delete ${title}?`, 'This action cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => void onDelete().catch((e) => setError(e.message)) }]);
  const removeDeadline = () => confirm('deadline', async () => { await deleteDeadline(deadlineId); router.back(); });
  return <Screen title="Deadline Detail" onBack={() => router.back()}><ErrorMessage message={error} />{deadline && <>
    <View style={styles.hero}><Text style={styles.title}>{deadline.title}</Text><Text style={styles.meta}>Due {new Date(deadline.due_at).toLocaleDateString()} · {deadline.progress}% complete</Text><View style={styles.progress}><View style={[styles.fill, { width: `${deadline.progress}%` }]} /></View><TextInput value={deadlineTitle} onChangeText={setDeadlineTitle} style={styles.input} placeholder="Deadline title" /><TextInput value={deadlineDate} onChangeText={setDeadlineDate} style={styles.input} placeholder="Due date (YYYY-MM-DD)" /><TextInput value={deadlinePriority} onChangeText={(v) => setDeadlinePriority(v.toUpperCase() as Priority)} style={styles.input} placeholder="Priority" /><View style={styles.actions}><ActionButton title="Save deadline" loading={loading} onPress={() => void saveDeadline()} /><ActionButton title="Delete deadline" secondary onPress={removeDeadline} /></View></View>
    <View style={styles.form}><Text style={styles.section}>{milestoneId ? 'Edit milestone' : 'Add milestone'}</Text><TextInput value={milestoneTitle} onChangeText={setMilestoneTitle} style={styles.input} placeholder="Milestone title" /><TextInput value={milestoneDate} onChangeText={setMilestoneDate} style={styles.input} placeholder="Target date (YYYY-MM-DD)" /><View style={styles.actions}><ActionButton title={milestoneId ? 'Save milestone' : 'Add milestone'} onPress={() => void saveMilestone()} />{milestoneId && <ActionButton title="Cancel" secondary onPress={() => { setMilestoneId(null); setMilestoneTitle(''); setMilestoneDate(''); }} />}</View></View>
    <View style={styles.form}><Text style={styles.section}>{taskId ? 'Edit task' : 'Add task'}</Text><TextInput value={taskMilestoneId} onChangeText={setTaskMilestoneId} style={styles.input} placeholder="Milestone ID (auto-filled when using Add task)" /><TextInput value={taskTitle} onChangeText={setTaskTitle} style={styles.input} placeholder="Task title" /><TextInput value={taskPriority} onChangeText={(v) => setTaskPriority(v.toUpperCase() as Priority)} style={styles.input} placeholder="Priority" /><View style={styles.actions}><ActionButton title={taskId ? 'Save task' : 'Add task'} onPress={() => void saveTask()} />{taskId && <ActionButton title="Cancel" secondary onPress={() => { setTaskId(null); setTaskTitle(''); }} />}</View></View>
    <Text style={styles.section}>Milestones</Text>{deadline.milestones?.map((m: any) => <View key={m.id} style={styles.card}><View style={styles.row}><View style={styles.main}><Text style={styles.cardTitle}>{m.title}</Text><Text style={styles.meta}>{m.progress}% · target {new Date(m.target_at).toLocaleDateString()}</Text></View><View style={styles.actions}><ActionButton title="Edit" secondary onPress={() => { setMilestoneId(m.id); setMilestoneTitle(m.title); setMilestoneDate(dateOnly(m.target_at)); }} /><ActionButton title="Delete" secondary onPress={() => confirm('milestone', async () => { await deleteMilestone(m.id); await load(); })} /></View></View>{m.tasks?.map((t: any) => <View key={t.id} style={styles.task}><TouchableOpacity style={styles.main} onPress={() => router.push(`/task/${t.id}` as any)}><Text style={styles.taskTitle}>{t.title}</Text><Text style={styles.meta}>{t.current_progress}%</Text></TouchableOpacity><View style={styles.actions}><ActionButton title="Edit" secondary onPress={() => { setTaskId(t.id); setTaskMilestoneId(m.id); setTaskTitle(t.title); setTaskPriority(t.priority ?? 'MEDIUM'); }} /><ActionButton title="Delete" secondary onPress={() => confirm('task', async () => { await deleteTask(t.id); await load(); })} /></View></View>)}<ActionButton title="Add task" secondary onPress={() => { setTaskId(null); setTaskMilestoneId(m.id); setTaskTitle(''); }} /></View>)}
    <ActionButton title="Plan a session" onPress={() => router.push('/session/plan' as any)} />
  </>}</Screen>;
}
const styles = StyleSheet.create({ hero: { backgroundColor: colors.surface, borderRadius: 24, padding: 24, gap: 10 }, form: { backgroundColor: colors.surface, borderRadius: 20, padding: 18, gap: 10 }, title: { fontSize: 28, fontWeight: '800', color: colors.text }, meta: { color: colors.muted }, input: { height: 44, borderWidth: 1, borderColor: colors.border, borderRadius: 12, paddingHorizontal: 12, color: colors.text }, progress: { height: 8, borderRadius: 4, backgroundColor: colors.border, overflow: 'hidden' }, fill: { height: '100%', backgroundColor: colors.primary }, section: { color: colors.text, fontSize: 20, fontWeight: '800' }, card: { backgroundColor: colors.surface, borderRadius: 20, padding: 18, gap: 12 }, cardTitle: { color: colors.text, fontSize: 18, fontWeight: '700' }, task: { borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12, flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, taskTitle: { color: colors.text, fontWeight: '600' }, main: { flex: 1, gap: 6 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, actions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' } });
