import { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { deleteTask, getTask, updateTask, type Priority } from '@/features/plans/api';
import { Screen, ErrorMessage } from '@/components/ui/Screen';
import { ActionButton } from '@/components/ui/ActionButton';
import { colors } from '@/theme/colors';
import { flowRoutes } from '@/features/navigation/flow';

const priorities: Priority[] = ['LOW', 'MEDIUM', 'HIGH'];
export default function TaskDetail() {
  const { taskId } = useLocalSearchParams<{ taskId: string }>(); const router = useRouter();
  const [task, setTask] = useState<any>(); const [title, setTitle] = useState(''); const [priority, setPriority] = useState<Priority>('MEDIUM'); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const load = async () => { try { const data: any = await getTask(taskId); setTask(data); setTitle(data.title); setPriority(data.priority ?? 'MEDIUM'); } catch (e: any) { setError(e.message); } };
  useEffect(() => { void load(); }, [taskId]);
  const save = async () => { setLoading(true); try { await updateTask(taskId, { milestone_id: task.milestone_id, title, priority }); await load(); } catch (e: any) { setError(e.message); } finally { setLoading(false); } };
  const remove = () => Alert.alert('Delete task?', 'This also removes planned sessions.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await deleteTask(taskId); router.back(); } catch (e: any) { setError(e.message); } } }]);
  return <Screen title="Task" onBack={() => router.back()}><ErrorMessage message={error} />{task && <View style={styles.content}><Text style={styles.project}>PROJECT TASK</Text><Text style={styles.title}>{task.title}</Text><Text style={styles.meta}>▱  {task.milestone_title ?? 'Project milestone'}</Text><View style={styles.progressCard}><View style={styles.circle}><Text style={styles.percent}>{task.current_progress ?? 0}%</Text><Text style={styles.progressLabel}>PROGRESS</Text></View><Text style={styles.stageLabel}>Current Stage</Text><Text style={styles.stage}>{task.current_progress >= 80 ? 'Final polish' : 'In progress'}</Text><View style={styles.track}><View style={[styles.fill, { width: `${task.current_progress ?? 0}%` }]} /></View></View><TextInput value={title} onChangeText={setTitle} style={styles.input} placeholder="Task title" /><Text style={styles.section}>Priority</Text><View style={styles.priorityRow}>{priorities.map((value) => <Pressable key={value} onPress={() => setPriority(value)} style={[styles.priority, priority === value && styles.priorityActive]}><Text style={[styles.priorityText, priority === value && styles.priorityTextActive]}>{value}</Text></Pressable>)}</View><Text style={styles.section}>Session history</Text>{task.sessions?.map((s: any) => <View key={s.id} style={styles.session}><Text style={styles.sessionTitle}>{s.status}</Text><Text style={styles.meta}>{s.estimated_minutes} minutes · {new Date(s.planned_start_at).toLocaleString()}</Text></View>)}<ActionButton title="Save task" loading={loading} onPress={() => void save()} /><ActionButton title="Plan Next Session" onPress={() => router.push(`/session/plan?taskId=${taskId}` as any)} /><ActionButton title="Delete task" secondary onPress={remove} /></View>}</Screen>;
}
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 32 }, project: { color: colors.muted, fontSize: 13, fontWeight: '800', letterSpacing: 2 }, title: { color: colors.text, fontSize: 34, fontWeight: '800' }, meta: { color: colors.muted, fontSize: 16 }, progressCard: { backgroundColor: colors.surface, borderRadius: 26, padding: 24, alignItems: 'center', gap: 10 }, circle: { width: 170, height: 170, borderRadius: 85, borderWidth: 12, borderColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, percent: { color: colors.primary, fontSize: 38, fontWeight: '800' }, progressLabel: { color: colors.text, fontSize: 13, letterSpacing: 2 }, stageLabel: { alignSelf: 'flex-start', color: colors.text, fontSize: 18, fontWeight: '700', marginTop: 10 }, stage: { alignSelf: 'flex-end', color: colors.muted, fontSize: 17, fontStyle: 'italic', marginTop: -30, marginBottom: 12 }, track: { width: '100%', height: 10, backgroundColor: '#E5E7EB', borderRadius: 99, overflow: 'hidden' }, fill: { height: '100%', backgroundColor: colors.primary }, input: { height: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 14, color: colors.text }, section: { color: colors.text, fontSize: 20, fontWeight: '800', marginTop: 8 }, priorityRow: { flexDirection: 'row', gap: 10 }, priority: { flex: 1, padding: 14, borderRadius: 14, borderWidth: 1, borderColor: colors.border, alignItems: 'center' }, priorityActive: { backgroundColor: colors.primary, borderColor: colors.primary }, priorityText: { color: colors.text, fontWeight: '700' }, priorityTextActive: { color: '#FFF' }, session: { backgroundColor: colors.surface, borderRadius: 18, padding: 16, gap: 6 }, sessionTitle: { color: colors.text, fontWeight: '800' } });
