import { apiRequest } from '../../lib/api-client';
export type CreateSessionInput = { task_id: string; planned_start_at: string; estimated_minutes: number; focus_mode: 'NORMAL' | 'HIGH'; is_follow_up?: boolean; previous_session_id?: string | null };
export const createSession = (input: CreateSessionInput) => apiRequest('/api/v3/sessions', { method: 'POST', body: JSON.stringify(input) });
export const getSession = (id: string) => apiRequest(`/api/v3/sessions/${id}`);
export const getTodaySessions = () => apiRequest('/api/v3/dashboard/today');
export const startSession = (id: string) => apiRequest(`/api/v3/sessions/${id}/start`, { method: 'POST' });
export const pauseSession = (id: string) => apiRequest(`/api/v3/sessions/${id}/pause`, { method: 'POST' });
export const resumeSession = (id: string) => apiRequest(`/api/v3/sessions/${id}/resume`, { method: 'POST' });
export const endSession = (id: string, endedEarly: boolean) => apiRequest(`/api/v3/sessions/${id}/end?ended_early=${endedEarly}`, { method: 'POST' });
export const rescheduleSession = (id: string, planned_start_at: string) => apiRequest(`/api/v3/sessions/${id}`, { method: 'PUT', body: JSON.stringify({ planned_start_at }) });
export const cancelSession = (id: string) => apiRequest(`/api/v3/sessions/${id}`, { method: 'DELETE' });
